### ISSUE TITLE
请求获得Psessionid时反错误码10001

### ISSUE THREAD

**Issue by xytianya** [515924628/qqrobot#1]
您好，参考了您的代码，但是在登录的第四步getUinAndPsessionid时，没有返回Psessionid，反错误码10001,我看了请求的参数都和正常登录WEB QQ时的请求参数相同，请问您有碰到类似问题么？谢谢

**Comment by radius-yf** [comment]
错误码10001应该是缺少cookie，你仔细检查一下吧

**Comment by xytianya** [comment]
Thanks A lot.
